services:
  app:
    container_name: trireme_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.docker  
    volumes:
      - ./frontend/dist:/frontend/dist
    networks:
      - trireme_network

  frontend:
    container_name: trireme_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - app 
    networks:
      - trireme_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: lklq
      POSTGRES_PASSWORD: "88888888"
      POSTGRES_DB: trireme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trireme_network

  locust:
    image: locustio/locust
    container_name: locust
    volumes:
      - ./locust:/mnt/locust:rw
      - ./locust/test_files:/mnt/test_files
    working_dir: /mnt/locust
    networks:
      - trireme_network
    ports:
      - "8089:8089"
    depends_on:
      - app
    command: -f /mnt/locust/locustfile.py --host http://app:8000

volumes:
  postgres_data:
    driver: local

networks:
  trireme_network:
    driver: bridge


  
