services:
  app:
    container_name: trireme_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.docker  
    volumes:
      - ./frontend/dist:/frontend/dist
    # networks:
    #   - ollama_network

  frontend:
    container_name: trireme_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Map Angular app to port 4200
    depends_on:
      - app  # Ensure the backend is up before the frontend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: lklq
      POSTGRES_PASSWORD: "88888888"
      POSTGRES_DB: trireme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - ollama_network

# networks:
#   ollama_network:
#     external: true

volumes:
  # ollama:
  #   driver: local
  postgres_data:
    driver: local
  # codestral: 
  #   driver: local

  
