services:
  app:
    container_name: trireme_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.docker  
    volumes:
      - ./frontend/dist:/frontend/dist

  frontend:
    container_name: trireme_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - app 

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: lklq
      POSTGRES_PASSWORD: "88888888"
      POSTGRES_DB: trireme_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local


  
